version: '3'

services:
  db:
    image: postgres:15-alpine3.18
    restart: always
    ports:
      - "54322:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=kitchen
