spring:
  application:
    name: feedback
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/feedback
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
server:
  port: 8084

